# Generated by Django 3.0.7 on 2020-08-21 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('team_image', models.ImageField(blank=True, default='bracket/static/default-team-img.jpg', null=True, upload_to='bracket/static/uploads')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', unique=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='bracket.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='bracket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('info', models.TextField(max_length=500)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 11, 3, 1, 0))),
                ('slug', models.SlugField(default='', unique=True)),
                ('goal', models.IntegerField(default=100)),
                ('matchups', models.ManyToManyField(to='bracket.Matchup')),
            ],
        ),
    ]
