# Generated by Django 3.0.7 on 2020-08-20 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='teams',
        ),
        migrations.AddField(
            model_name='campaign',
            name='matchups',
            field=models.ManyToManyField(to='bracket.Matchup'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='matchup',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 20, 3, 32, 207849)),
        ),
    ]
