# Generated by Django 3.0.7 on 2020-08-20 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0002_auto_20200820_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 20, 8, 43, 415081)),
        ),
    ]
