# Generated by Django 3.0.7 on 2020-08-20 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0003_auto_20200820_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 20, 10, 46, 696226)),
        ),
    ]
